### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by farberm** [BuongiornoTexas/pwdusage#10]
I need some help with the install. I am working on synology docker system

1. Powerwall-Dashboard is working fine on synology docker
2. I did not alter fw rules cuz I think they are all allowed. I am on unifi and my grafana is on 192.168.2.113:9000
3. Ran Bash build.sh from usage-service directory
4. Created usage.json file by copying example_usage.json to usage.json
5. Edit usage.json to have Timezone as America/New_York. I left influx db as http://localhost:8086
6. Ran Bash test_service.sh. The result is

.....Usage Engine Status": "599 Error loading usage engine configuration file (<urllib3.connection.HTTPConnection object at 0x7fd1c7556350>: Failed to establish a new connection: [Errno 111] Connection refused).

When I run the bash test_service.sh I have this in the terminal
Enter y/Y to run test> y
pwdusage
pwdusage
5208ea26bee5f86e1de6bf95479c3f428ba6f6f6bd5be994c9d07e9812fb6a34

.

Is this a few rule issue, or something else?

Thanks for your help

**Comment by BuongiornoTexas** [comment]
Hi @farberm, before we go down the path of troubleshooting, can I check that you can't install one of jason's preconfigured docker images? Also, can I confirm that your tariff model matches what is available in the usage engine at the moment? If you are in an American timezone, you may well have billing models that don't match up (I've implemented one very standard australian tariff set).

The error message could be a couple of things - maybe firewall (try http://<host>:9050/usage_engine), maybe a problem with the configuration file permissions, and maybe the file itself. Have you done the various steps in the docs for grafana setup? In particular is the JSON datasource working (( suspect not from your description).

Also, when you updated the usage.json, did you either update the influx host and/or check that localhost:8086 works?

**Comment by farberm** [comment]
1. ok... I was able to get bash test_service.sh to work with the following response...
{"Usage Engine Status": "Engine OK, tariffs (re)loaded"}... 

I had to input the IP address of the influxdb from docker - 172.20.0.6:8086

2. I have included a link to my usage.json file. I think I have it all set correctly

https://www.dropbox.com/scl/fi/25mjyqukmzi8sdb249tkr/usage.json?rlkey=5l3dnqjh2qv4qv1izpgebd4a9&dl=0

3. I also changed the json file location. (/volume1/docker/Powerwall-Dashboard/tools/usage-service/usage.json)
I also change the path in the docker settings for pwdusage container to match using envir variable USAGE_JSON

4. Here is the extend.yml file link...https://www.dropbox.com/scl/fi/np6z52o5zwx7iz2gk3e6k/pwdusage.extend.yml?rlkey=n95oove81le6is9igziiltv92&dl=0

I still get Gateway TImeout error when I go to set up the Grafana Database json

Thanks again... I am getting closer

**Comment by BuongiornoTexas** [comment]
Step 1 is good news, and I'm assuming usage.json is OK, or you probably wouldn't have got the message you did in step 1.

In step 3, did you copy the elements of pwdusage.extend.yml into powerwall.extend.yml in the Powerwall-Dashboard directory?  Also, you should revert USAGE_JSON in this file to /var/lib/pwdusage/usage.json - you need to point to the file in the docker file system, not your host filesystem (this may be the source of the problem?).

Can you also run through the steps in Datasource troubleshooting and report back?

**Comment by farberm** [comment]
1. Yes the pwdusage.extend.yml file is in the Powerwall-Dashboard directory. 
2. I edited it to have the /var/lib/pwdusage/usage.json. See below
3. The Docker container has the environ var added for USAGE_JSON as /volume1/docker/Powerwall-Dashboard/tools/usage-service/usage.json (This may be the issue)???
4. Datasource Troubleshooting
   a. Save and Test....I get Testing and then Gateway Timeout 
   b.  192.168.2.113:9050/usage_engine --> Site cannot be reached
   c.  Log for Docker says -Info Powerwal-Dashboard usage proxy server [1.0.0] HTTP port 9050 and Info Powerwal-Dashboard usage engine proxy started


version: "3.5"

services:
    pwdusage:
        image: jasonacox/pwdusage:latest
        container_name: pwdusage
        hostname: pwdusage
        restart: always
        user: "1000:1000"
        volumes:
            - type: bind
              source: ./tools/usage-service
              target: /var/lib/pwdusage
              read_only: true
        ports:
            - target: 9050
              published: 9050
              mode: host
        environment:
            - USAGE_JSON=/var/lib/pwdusage/usage.json
        depends_on:
            - influxdb

**Comment by BuongiornoTexas** [comment]
1. You need to copy or move the **contents** of pwdusage.extend.yml into powerwall.extend.yml.

4. You've quoted two different IP addresses - 172.20.0.6 & 192.168.2.113 - which one is hosting the pwdusage engine? (and did you modify the address in the grafana setup page?).

It sounds like you are not far off though!

**Comment by farberm** [comment]
. I apologize. My prior msg should have said the powerwall.extend.yml file was edited. I included the file contents in the prior email.
2. The 172.20.0.6 is the IP address of the influxdb. The 192.168.2.113 is hosting the pwdusage engine. That is what I check when I eun the test_service command

**Comment by BuongiornoTexas** [comment]
Ok - there's something I don't understand at this point. If test_service.sh worked, then I would expect the datasource to work as well. I know you have done it already, but can you please retry the following to check if any of the changes you made yesterday have affected things:

1. Run bash text_service.sh and check 192.168.2.113:9050/usage_engine in a web browser.
2. If that goes well (and before ending the test_service), try and add the grafana datasource - make sure the url for the data source is set to 192.168.2.113:9050/usage_engine. 

Hopefully this will give us a bit more information for debugging.

**Comment by farberm** [comment]
1. Response from test_servie.sh --> http://192.168.2.113:9050/uage_engine-->
 {"Usage Engine Status": "Engine OK, tariffs (re)loaded"}
2. Result from Grafana json datasouce (192.168.2.113:9050/usage_engine --Gateway Timeout

**Comment by farberm** [comment]
Is there possibly an issue where I have the usage.json file. Right now it is located in the usage-service folder. I therefore set the envir var USAGE_JSON to /volume1/docker/Powerwall-Dashboard/tools/usage-service/usage.json....

**Comment by farberm** [comment]
I see this error in my log file in synology. The container starts ok then give me this when I try to set up the datasource...Specify 'USAGE_JSON' environment variable, provide 'usage.json' file in working directory, or provide valid path for CLI version.

**Comment by BuongiornoTexas** [comment]
@farberm - OK - the synology is giving us some useful info and I think we can fix that (see next post). Before we try that, can I reconfirm that when you ran the test you did the following:

- Ran test_service.sh
- While test_service.sh was running, opened the browser to http://192.168.2.113:9050/uage_engine and got the Engine OK message?
- While test_service.sh was running, tried to set up the data source?

Sorry for being so careful about this - I'm was really expecting that either both steps would work, or neither would work, so the result you are reporting is throwing me.

**Comment by BuongiornoTexas** [comment]
On the USAGE_JSON, have you specified this in the command line as well as in the .yml file? It should only be specified once - ideally in the .yml file. The following may help resolve the issue:

- Both your synology system and your docker container have separate file systems. The /volume1... is the synology (host) filesystem, while the /var/lib is the container (target system). 
- The .yml file tells the container how to map a folder from the host so that the target can see the .json file.
- USAGE_JSON tells the container where the file is in the target file system. For your setup, this should be the /var/lib... version.

**Comment by farberm** [comment]
Sorry for having this issue.... This is what I observe....
1. I have pwdusage container running on docker.  
2. ssh into my synology NAS and goto folder usage-service
3. run bash test_service.sh
4. I then see the current container stop and a new one start
5. I wait a few minutes and then goto HTTP://192.168.2.113:9050/usage_engine
6. I then receive the OK statement
7. When I go to my grafana set up (192.168.2.113:900) and add the new JSON database is goes to testing and then time out.

Quick question for the user ID in powerwall.extend.yml.. is the line user: 1000:1000 supposed to be UID:GID? or both UID? I have tried both but I think it should be UID GID which is 1026:100 for me

**Comment by farberm** [comment]
> On the USAGE_JSON, have you specified this in the command line as well as in the .yml file? It should only be specified once - ideally in the .yml file. The following may help resolve the issue:
> 
> * Both your synology system and your docker container have separate file systems. The /volume1... is the synology (host) filesystem, while the /var/lib is the container (target system).
> * The .yml file tells the container how to map a folder from the host so that the target can see the .json file.
> * USAGE_JSON tells the container where the file is in the target file system. For your setup, this should be the /var/lib... version.

Inthe powerwall.extend.yml file it is .....
environment:
            - USAGE_JSON=/var/lib/pwdusage/usage.json
  In the container setuo I specify    it as /volue1/docker....

So I should remove it from the container envir setting?

**Comment by BuongiornoTexas** [comment]
In step 7, you have the address as 192.168.2.113:900 - I'm assuming this is a typo and the address is: 192.168.2.113:9050/usage_engine?

> So I should remove it from the container envir setting?

At very least, both should be the same and point the /var/lib version  - I'd start by deleting it and seeing what happens.

On UID/GID, give it a try. What's the worst that could happen? It probably should match UID/GID settings in the powerwall.yml file.

**Comment by farberm** [comment]
Yes step 7 typo 9050
ok its 1000:1000 in the powerwall.yml... I will see if that makes difference. I am restarting the NAS just to make sure I clear things out.

**Comment by farberm** [comment]
ok restarted and unfortunately get the same findings
After restart of NAS ....point web browser to http://192.168.2.113:9050/usage_engine and get the "Usage Engine OK"
go to Grafana setup for Datasource enter http://192.168.2.113:9050/usage_engine...click save and test....get Testing... and then Gateway Timeout

I can do a remote session if that would hep and you have the time?

**Comment by BuongiornoTexas** [comment]
> I can do a remote session if that would hep and you have the time?

Unfortunately, I don't think I can carve that  out. I also suspect I'm not familiar enough with synology to be useful with hands on. 

How about you post your current usage.json and I'll test it in my setup? We can at least eliminate pwdusage config issues that way.

**Comment by BuongiornoTexas** [comment]
Can you also send through a screen shot of your datasource setup page?

**Comment by farberm** [comment]
> Can you also send through a screen shot of your datasource setup page?

Yes Iwill shortly. I am doing a fresh install to make sure I follow all the step again

**Comment by farberm** [comment]
Here is my usage.json file ( the name in the usage-service folder is usage.json) and an  image on Grafana. I did a complete reinstall and now I cannot get the engine to say ok even with test_service...

"Usage Engine Status": "599 Error loading usage engine configuration file (Usage engine JSON configuration file not found.\nSpecify 'USAGE_JSON' environment variable, provide 'usage.json' file in working directory, or provide valid path for CLI version.)."}

Maybe its a problem with my usage.json file?

<img width="759" alt="Screenshot 2024-11-11 at 10 24 43 PM" src="https://github.com/user-attachments/assets/82cd1cb3-29df-4095-a823-c289e942ce03">


https://www.dropbox.com/scl/fi/n1ak0jce2055kqj3bpfww/usage-Duke.json?rlkey=f5q5e45zz9y67sxatgeji6drw&dl=0

**Comment by BuongiornoTexas** [comment]
@farberm - I'm afraid I'm going to have to pause for a bit. I probably won't be able to pick up again for two days. In the meantime:

- From first look, your json is OK. I'll test it in my system when I get a chance.
- Did you run the test_service in the tools/usage-service folder and/or did you have a copy of usage.json in the folder you ran test_service from?

**Comment by BuongiornoTexas** [comment]
Oh yeah - the datasource looks 100% correct!

**Comment by farberm** [comment]
I ran the test_service from the usage-service folder and I had a copy of the usage.json file in that folder when I ran it.

test_servicce  now tests ok when I run it. The issue I think was when I restarted the influxdb changed IP to 172.20.0.3/80806 instead of 172.20.0.6:8086... I tried running with 127.0.0.1:8086 and that does not work.

Take you time no rush... I will be gone next week so will be some time before I can pick back up anyways

**Comment by farberm** [comment]
SUCCESS!!!!
While I can test the test_service by going to 192.168.2.113:9050/usage_engine… I had to use the ip address of the container like I had to do for influxdb. When I put in 172.17.0.5:9050/usage_engine…The data source is working.

Now on to adding the dashboards….

I will send a msg to Jason Cox to see if he has an explanation as to why I need to use the ip address fo the container instead of the NAS… I might need to set the netowrk to host instead of bridge?

**Comment by BuongiornoTexas** [comment]
Ah - OK, that makes sense (sort of), and isn't something that I was going to be able to resolve. I don't thing this is a Jason problem - it sounds more like an issue with the way synology's version of docker handles port mapping. I'm pretty the standard for the current version does this without needing anything else (i.e. you make a call to the host and the relevant docker container picks up the info).

I would tend to start by doing a bit of reading on the limits of docker on synology (I know there are **LOTS** of idiosyncracies with synology.

Please mark this as closed if you are happy we are sorted - raise a new issue if you have follow ups on the dashboards.

**Comment by farberm** [comment]
Ok will mark as resolved. I will play around with how the network option is used and see if I change it from bridge to maybe host if I can make a difference
