### ISSUE TITLE
PWSTATS setup (adapting config files)

### ISSUE THREAD

**Issue by michalperth** [BuongiornoTexas/pwdusage#11]
Moved from jasonacox/pypowerwall  repo.
...  I have 3 pricing periods for the whole year (no season usage)
09.00 -> 15.00 : Super Off peak $ 0.08
15.00-> 21.00 : Peak $ 0.52
21.00-> 09.00 : Mid Peak $ 0.20
I'm not getting paid any In feed tariff ($ 0.00 ).
In the example_usage.jason you defined the 4 periods:
"22:00": "Off-Peak",
"08:00": "Peak",
"11:00": "Off-Peak",
"17:00": "Peak"
Can I just rename the first 3 periods to suit my needs and do something like this:
"09:00": "Super Off-Peak
"15:00": "Peak"
"21:00": "Mid-Peak"
and what to do with the existing 4th defined period? Does anything also needs to be changed in other file(s) to follow this?
I can see that the other parts of this file needs to be altered as well but let's start from the basics.

Also, what is the meaning (and importance ) of:
"week_anchor": "MONTH",
"year_anchor": "JUN"
?
Thank you.

PS. thanks for the comment and your time in the other thread. I closed it as suggested.

**Comment by michalperth** [comment]
Hi,
I preppared the modified example_usage.jason to suit my needs. Can someone with the experience verify if it does make sense please.
Also, what is the purpose and meaning of ""calendar": {  "2024-11-19": ..." ?

{
    "settings": {
        "influx_url": "http://localhost:8086",
        "bucket": "powerwall/kwh",
        "timezone": "Australia/Perth",
        "supply_priority": [
            "GRID_SUPPLY",
            "PW_SUPPLY",
            "SOLAR_SUPPLY"
        ],
        "cost_unit": "$",
        "energy_unit": "kWh",
        "rename": {
            "GRID_SUPPLY": "Grid supply---",
            "GRID_EXPORT": "Grid export+++"
        },
        "resample": true,
        "week_anchor": "MONTH",
        "year_anchor": "JANUARY"        
    },
    "plans": [
        {
            "name": "Synergy_Midday-Saver",
            "report": [
                "GRID_SUPPLY",
                "GRID_EXPORT",
                "SELF_PW_NET_OF_GRID",
                "SELF_SOLAR_PLUS_RES"
            ],
            "agent": "Simple",
            "seasons": {
                "All_Year": [
                    {
                        "schedule": "Week",
                        "days": [
                            0,
                            1,
                            2,
                            3,
                            4,
                            5,
                            6
                        ],
                        "periods": {
                            "09:00": "Off-Peak",
                            "15:00": "Peak",
                            "21:00": "Mid-Peak"
                        }
                    }
                ]
            }
        }
    ],
    "calendar": {
        "2024-11-19": {
            "plan": "Synergy_Midday-Saver",
            "season": "All_Year",
            "tariffs": {
                "Peak": {
                    "GRID_SUPPLY": -0.525313,
                    "GRID_EXPORT": 0.00,
                    "SELF_PW_NET_OF_GRID": 0.525313,
                    "SELF_SOLAR_PLUS_RES": 0.525313,
                    "SUPPLY_CHARGE": -1.26075
                },
                "Mid-Peak": {
                    "GRID_SUPPLY": -0.231138,
                    "GRID_EXPORT": 0.00,
                    "SELF_PW_NET_OF_GRID": 0.231138,
                    "SELF_SOLAR_PLUS_RES": 0.231138,
                    "SUPPLY_CHARGE": -1.26075
                },
                "Off-Peak": {
                    "GRID_SUPPLY": -0.08405,
                    "GRID_EXPORT": 0.00,
                    "SELF_PW_NET_OF_GRID": 0.08405,
                    "SELF_SOLAR_PLUS_RES": 0.08405,
                    "SUPPLY_CHARGE": -1.26075
                }
            }
        }
    }
}

Thank you.

**Comment by michalperth** [comment]
and... we got first problem (I think):
michal@NUC:~/Powerwall-Dashboard/tools/usage-service$ bash test_service.sh
 
Warning for developers: this script will delete any existing pwdusage container.
However, is does not delete the pwdusage docker image.
For general end users, this is what you want to happen for trouble shooting.
 
Enter y/Y to run test> y
Error response from daemon: No such container: pwdusage
Error response from daemon: No such container: pwdusage
3f1091c46479d7989058d08e8453bccdc357fa4c42f9951bc298e154db82fefc
 
Waiting. Please hit enter to clean up test container.> 
pwdusage
pwdusage

the  previous bash build.sh went as follow:
michal@NUC:~/Powerwall-Dashboard/tools/usage-service$ bash build.sh
This script cleans up old versions of the pwdusage docker image,
and builds a new image using the latest version pwdusage from pypi.
Normal end users should enter 'y' when asked to clean up.
Developers should probably avoid this script - it's a bit terminal.
-------------------------------------------------------------------

Clean up old versions of pwusage before building? (Y/n)>y

Error response from daemon: No such container: pwdusage
Error response from daemon: No such container: pwdusage
Error response from daemon: No such image: jasonacox/pwdusage:latest
[+] Building 35.1s (8/8) FINISHED                                                                    docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                 0.1s
 => => transferring dockerfile: 411B                                                                                 0.0s
 => [internal] load metadata for docker.io/library/python:3.11-slim                                                 10.6s
 => [auth] library/python:pull token for registry-1.docker.io                                                        0.0s
 => [internal] load .dockerignore                                                                                    0.1s
 => => transferring context: 2B                                                                                      0.0s
 => [1/3] FROM docker.io/library/python:3.11-slim@sha256:370c586a6ffc8c619e6d652f81c094b34b14b8f2fb9251f092de23f16e  4.8s
 => => resolve docker.io/library/python:3.11-slim@sha256:370c586a6ffc8c619e6d652f81c094b34b14b8f2fb9251f092de23f16e  0.0s
 => => sha256:5f20101c4b63a3742b4155dcffc296c8ee0e2c7b83dbe6c7687441d991f358d4 250B / 250B                           0.7s
 => => sha256:51e2bd9c4b085ec5483ea37c7aff2b4fa3e49a780ff4db8f971fa68c9539db9c 16.20MB / 16.20MB                     3.4s
 => => sha256:3a75594a45d1452af40f08d7e4d4fa96572c3a09fb46ae142cf45e98973b3c69 3.32MB / 3.32MB                       2.4s
 => => sha256:bc0965b23a04fe7f2d9fb20f597008fcf89891de1c705ffc1c80483a1f098e4f 28.23MB / 28.23MB                     3.3s
 => => extracting sha256:bc0965b23a04fe7f2d9fb20f597008fcf89891de1c705ffc1c80483a1f098e4f                            0.6s
 => => extracting sha256:3a75594a45d1452af40f08d7e4d4fa96572c3a09fb46ae142cf45e98973b3c69                            0.1s
 => => extracting sha256:51e2bd9c4b085ec5483ea37c7aff2b4fa3e49a780ff4db8f971fa68c9539db9c                            0.4s
 => => extracting sha256:5f20101c4b63a3742b4155dcffc296c8ee0e2c7b83dbe6c7687441d991f358d4                            0.0s
 => [2/3] WORKDIR /app                                                                                               0.2s
 => [3/3] RUN pip3 install --no-cache-dir pwdusage                                                                  12.1s
 => exporting to image                                                                                               6.9s 
 => => exporting layers                                                                                              5.3s 
 => => exporting manifest sha256:9691331f944d4828d5a4579f089b754b64b425c5fb99d4a5009bc8c9eb1c1697                    0.0s 
 => => exporting config sha256:c34ace2ef66f89042dce59c834094103057f23412b73e1cf675bf4b409a969da                      0.0s 
 => => exporting attestation manifest sha256:9d6e71268e0dae58823cd4bfcd760d2a8fbb55b2e9a35a8a05e19a77666ead84        0.1s
 => => exporting manifest list sha256:50211461f4ab4c107c8b0d303b16b544ad6d4d7d7a572f2b6ca20d874dbdba5c               0.0s
 => => naming to docker.io/jasonacox/pwdusage:latest                                                                 0.0s
 => => unpacking to docker.io/jasonacox/pwdusage:latest                                                              1.4s

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/fpf76yif0ogj3qojcntict89d

Thanks.

**Comment by michalperth** [comment]
When running the bash test_service.sh, I'm getting: 
2024-12-25 10:26:09 ERROR: Error loading usage engine configuration file.
2024-12-25 10:26:09 ERROR: Details: <urllib3.connection.HTTPConnection object at 0x7fa6e5bb6510>: Failed to establish a new connection: [Errno 111] Connection refused
?
EDIT: I run the test_service.sh under example_usage.jason where I only modified the time zone (Australia/Perth). Also, the pwdusage.extended.yml user was changed to 1000:1001 to suit what it is.
Thanks

**Comment by michalperth** [comment]
Also, not sure what it is but influxdb does not specify an user for that querry, is it the part of the problem?

~/Powerwall-Dashboard/tools/usage-service$ docker inspect $(docker ps -q) --format '{{.Config.User}} {{.Name}}'
 /pwdusage
1000:1001 /telegraf
1000:1001 /weather411
1000:1001 /pypowerwall
 /influxdb
1000:1001 /grafana

**Comment by BuongiornoTexas** [comment]
Please post your `pwdusage.extended.yml` and `usage.json` files. I'll check when I have time. (remove any login details - I don't think there are any though).

**Comment by michalperth** [comment]
Hi, thanks for  answering during this time of the year !
**pwdusage.extended..yml:**

1. version: "3.5"
2. 
3. services:
4.     pwdusage:
5.         image: jasonacox/pwdusage:latest
6.         container_name: pwdusage
7.         hostname: pwdusage
8.         restart: always
9.         user: "1000:1001"
10.         volumes:
11.             - type: bind
12.               source: ./tools/usage-service
13.               target: /var/lib/pwdusage
14.               read_only: true
15.         ports:
16.             - target: 9050
17.               published: 9050
18.               mode: host
19.         environment:
20.             - USAGE_JSON=/var/lib/pwdusage/usage.json
21.         depends_on:
22.             - influxdb

**usage.jason**

1. {
2.     "settings": {
3.         "influx_url": "http://localhost:8086",
4.         "bucket": "powerwall/kwh",
5.         "timezone": "Australia/Perth",
6.         "supply_priority": [
7.             "GRID_SUPPLY",
8.             "PW_SUPPLY",
9.             "SOLAR_SUPPLY"
10.         ],
11.         "cost_unit": "$",
12.         "energy_unit": "kWh",
13.         "rename": {
14.             "GRID_SUPPLY": "Grid supply---",
15.             "GRID_EXPORT": "Grid export+++"
16.         },
17.         "resample": true,
18.         "week_anchor": "MONTH",
19.         "year_anchor": "JUN"        
20.     },
21.     "plans": [
22.         {
23.             "name": "Aurora-TAS-ToU",
24.             "report": [
25.                 "GRID_SUPPLY",
26.                 "GRID_EXPORT",
27.                 "SELF_PW_NET_OF_GRID",
28.                 "SELF_SOLAR_PLUS_RES"
29.             ],
30.             "agent": "Simple",
31.             "seasons": {
32.                 "Summer": [
33.                     {
34.                         "schedule": "Weekday",
35.                         "days": [
36.                             0,
37.                             1,
38.                             2,
39.                             3,
40.                             4
41.                         ],
42.                         "periods": {
43.                             "22:00": "Off-Peak",
44.                             "08:00": "Peak",
45.                             "11:00": "Off-Peak",
46.                             "17:00": "Peak"
47.                         }
48.                     },
49.                     {
50.                         "schedule": "Weekend",
51.                         "days": [
52.                             5,
53.                             6
54.                         ],
55.                         "periods": {
56.                             "00:00": "Off-Peak"
57.                         }
58.                     }
59.                 ],
60.                 "Winter": [
61.                     {
62.                         "schedule": "Weekday",
63.                         "periods": {
64.                             "21:00": "Off-Peak",
65.                             "07:00": "Peak",
66.                             "10:00": "Off-Peak",
67.                             "16:00": "Peak"
68.                         }
69.                     }
70.                 ]
71.             }
72.         }
73.     ],
74.     "calendar": {
75.         "2022-10-06": {
76.             "plan": "Aurora-TAS-ToU",
77.             "season": "Summer",
78.             "tariffs": {
79.                 "Peak": {
80.                     "GRID_SUPPLY": -0.33399,
81.                     "GRID_EXPORT": 0.08883,
82.                     "SELF_PW_NET_OF_GRID": 0.33399,
83.                     "SELF_SOLAR_PLUS_RES": 0.33399,
84.                     "SUPPLY_CHARGE": -0.04579291666
85.                 },
86.                 "Off-Peak": {
87.                     "GRID_SUPPLY": -0.15551,
88.                     "GRID_EXPORT": 0.08883,
89.                     "SELF_PW_NET_OF_GRID": 0.15551,
90.                     "SELF_SOLAR_PLUS_RES": 0.15551,
91.                     "SUPPLY_CHARGE": -0.04579291666
92.                 }
93.             }
94.         },
95.         "2023-04-02": {
96.             "season": "Winter"
97.         }
98.     }
99. }

Thanks.

**Comment by BuongiornoTexas** [comment]
Take a quick look at issue #10 - the same error came up and the debug steps there may sort you out.

**Comment by BuongiornoTexas** [comment]
Also, if the influx ip address works correctly, try replacing it with the name of the machine hosting docker - e.g. in my case orac.local (this is going to depend on your LAN/Wireless DNS working though).

**Comment by michalperth** [comment]
Hi,
still, no success
2024-12-26 19:54:58 INFO: Powerwall-Dashboard usage proxy server [1.0.0] - HTTP Port 9050
2024-12-26 19:54:58 INFO: Powerwall-Dashboard usage engine proxy Started
2024-12-26 19:56:42 ERROR: Error loading usage engine configuration file.
2024-12-26 19:56:42 ERROR: Details: <urllib3.connection.HTTPConnection object at 0x7fc241e36e10>: Failed to establish a new connection: [Errno 111] Connection refused

**Comment by michalperth** [comment]
so what about that ERROR: Error loading usage engine configuration file ?
Which file is that, where it should be located/copied to?
Thanks

**Comment by michalperth** [comment]
the docker internal addresses are:
influxdb: 172.18.0.6
telegraf: 172.18.0.5
grafana: 172.18.0.4
I can play with them, but I need to know where to use it.
Thanks

**Comment by michalperth** [comment]
now, if I put "influx_url": "http://172.18.0.6:8086" in usage.jason, I get:

"599 Error loading usage engine configuration file ((<urllib3.connection.HTTPConnection object at 0x7f69dcccd6d0>, 'Connection to 172.18.0.6 timed out. (connect timeout=10.0)'))."

So no more "refused" but "timed out"

2024-12-26 23:02:46 ERROR: Error loading usage engine configuration file.
2024-12-26 23:02:46 ERROR: Details: (<urllib3.connection.HTTPConnection object at 0x7f3ef5ae2f90>, 'Connection to 172.18.0.6 timed out. (connect timeout=10.0)')

thanks

**Comment by michalperth** [comment]
![Screenshot from 2024-12-26 22-38-26](https://github.com/user-attachments/assets/d863681f-db9a-4444-9861-30f97380c5d0)

Those are the files permissions in the /var/lib/pwdusage, that looks ok I hope.

**Comment by michalperth** [comment]
and the influxdb is listening on 8086...

2024-12-26 23:43:40 ts=2024-12-26T15:43:40.962854Z lvl=info msg="Listening on HTTP" log_id=0thv2XDW000 service=httpd addr=[::]:8086 https=false

I restarted the influxdb then pwdusage and finally tried to load the http, no progress. I'm running out of ideas, there is not even a trace of connecting attempts in the influxdb logs. Time for bed.
Thanks

**Comment by BuongiornoTexas** [comment]
Michal, you need to set the influxdb url to the IP address of the docker host, not the internal docker IP i.e. http://\<host ip\>:8086.

**Comment by michalperth** [comment]
Hi,
new day, new challanges :)
so, I put in usage.jason: "influx_url": "http://nuc:8086"
and in the local browser: http://192.168.9.245:9050/usage_engine
that resulted in: Usage Engine Status	"Engine OK, tariffs (re)loaded"

Time to follow the rest of the steps... :)
EDIT: I should mention that in the meanwhile I coppied the pwdusage.extend.yml to the Powerwall-Dashboard directory. Has it something to do with a success? No idea...
EDIT2: I was able to get positive resoult from the other PC. then reload on both, host and remote PC's results in the error Read timed out. (read timeout=0)). Looks like the influxdb is somehow having a problem.
2024-12-27 08:23:13 ERROR: Details: <urllib3.connection.HTTPConnection object at 0x7f66f07c9d50>: Failed to resolve 'nuc' ([Errno -3] Temporary failure in name resolution). Every attempt now is a failure:
2024-12-27 08:37:23 ERROR: Error loading usage engine configuration file.
2024-12-27 08:37:23 ERROR: Details: HTTPConnectionPool(host='nuc', port=8086): Read timed out. (read timeout=0)
thanks

**Comment by michalperth** [comment]
I changed it to "influx_url": "http://192.168.9.245:8086/" and it works again. Hmmm....
Usage Engine Status	"Engine OK, tariffs (re)loaded"

**Comment by michalperth** [comment]
OK, after finishing the test, I did:
./compose-dash.sh stop
./compose-dash.sh up -d
which went trough with no problems. I noticed thou, that the jasonacox/pwdusage (latest) is not running.
Is that how it should be?
Thanks
![Screenshot from 2024-12-27 09-15-54](https://github.com/user-attachments/assets/6020a76a-18fb-4e87-9e8d-a6389c9f0fbd)

**Comment by BuongiornoTexas** [comment]
> I changed it to "influx_url": "http://192.168.9.245:8086/" and it works again. Hmmm....

So your problem with the `nuc` url is a problem with name resolution on your local network. Which I can't help with - you'll need to check your router docs and do some more general reading on this. However, if your nuc has a static ip, then there is no problem with just using that (and you know it works). 

> I noticed thou, that the jasonacox/pwdusage (latest) is not running.

Sorry - I gave incomplete instructions - check this for setting up the .extend file. https://github.com/BuongiornoTexas/pwdusage?tab=readme-ov-file#add-pwdusage-to-powerwall-dashboard

**Comment by michalperth** [comment]
Thanks for that.
Actually, when I used "nuc", it was the first tiime I got:
 Usage Engine Status "Engine OK, tariffs (re)loaded".
It stopped working thou after subsequent page reloads. Go figure!
I can use "nuc" for enything else so I don't understand what is happening. There is a discussion at https://github.com/influxdata/influxdb/issues/15321 (if you interested) about influx troubles itself.
Going to read the link you posted now!
Thanks

**Comment by michalperth** [comment]
Update:
the pwdusage is running now in docker
I was able to add data source in grafana (2 green info squares shown up on saving)
I succesfully tested http://192.168.9.245:9050/usage_engine,  Usage Engine Status	"Engine OK, tariffs (re)loaded"
Now I will try to get the data to actually display in the Grafana browser screen.
Thanks.

**Comment by michalperth** [comment]
Hi,
just probably one querry before I close that thread. I did some changes in the use.jason to adopt to my Synergy plan.
Can you please have a glimpse at it and let me know if it does have a chance to work. That file is currently in use but I can't see if it is ok before I set up new a dashboard in Grafana (which is the new, uncharted territory for me!).
Anyway, I got 3, daily price brackets, no seazons, no weekends, zero export $, 24/7. And that is what I did:

{
    "settings": {
        "influx_url": "http://192.168.9.245:8086",
        "bucket": "powerwall/kwh",
        "timezone": "Australia/Perth",
        "supply_priority": [
            "GRID_SUPPLY",
            "PW_SUPPLY",
            "SOLAR_SUPPLY"
        ],
        "cost_unit": "$",
        "energy_unit": "kWh",
        "rename": {
            "GRID_SUPPLY": "Grid supply---",
            "GRID_EXPORT": "Grid export+++"
        },
        "resample": true,
        "week_anchor": "MONTH",
        "year_anchor": "JAN"        
    },
    "plans": [
        {
            "name": "Synergy_Midday-Saver",
            "report": [
                "GRID_SUPPLY",
                "GRID_EXPORT",
                "SELF_PW_NET_OF_GRID",
                "SELF_SOLAR_PLUS_RES"
            ],
            "agent": "Simple",
            "seasons": {
                "All_Year": [
                    {
                        "schedule": "Week",
                        "days": [
                            0,
                            1,
                            2,
                            3,
                            4,
                            5,
                            6
                        ],
                        "periods": {
                            "09:00": "Off-Peak",
                            "15:00": "Peak",
                            "21:00": "Mid-Peak"
                        }
                    }
                ]
            }
        }
    ],
    "calendar": {
        "2024-11-19": {
            "plan": "Synergy_Midday-Saver",
            "season": "All_Year",
            "tariffs": {
                "Peak": {
                    "GRID_SUPPLY": -0.525313,
                    "GRID_EXPORT": 0.00,
                    "SELF_PW_NET_OF_GRID": 0.525313,
                    "SELF_SOLAR_PLUS_RES": 0.525313,
                    "SUPPLY_CHARGE": -1.26075
                },
                "Mid-Peak": {
                    "GRID_SUPPLY": -0.231138,
                    "GRID_EXPORT": 0.00,
                    "SELF_PW_NET_OF_GRID": 0.231138,
                    "SELF_SOLAR_PLUS_RES": 0.231138,
                    "SUPPLY_CHARGE": -1.26075
                },
                "Off-Peak": {
                    "GRID_SUPPLY": -0.08405,
                    "GRID_EXPORT": 0.00,
                    "SELF_PW_NET_OF_GRID": 0.08405,
                    "SELF_SOLAR_PLUS_RES": 0.08405,
                    "SUPPLY_CHARGE": -1.26075
                }
            }
        }
    }
}

It would be great if you can comment. If all good I will close this thread and probably open one for the implementation in Grafana. You gave pretty good decription but I'm missing the very basic stuff.
Thanks

**Comment by michalperth** [comment]
I just find out from the other closed thread that the supply charge is based on the hourly calculation so I will need to correct this.
Edit: is there any decimal point limit at all?
Thanks.

**Comment by michalperth** [comment]
So I got everything running in the end.
Thanks for the excellent utility and your support 😀

**Comment by BuongiornoTexas** [comment]
Excellent - I took a quick look at your json file, and it looks correct.
