### ISSUE TITLE
Help understanding usage.json and what mistake I am making

### ISSUE THREAD

**Issue by farberm** [BuongiornoTexas/pwdusage#12]
This is a terrific setup with great documentation which I have read. 

**Question #1.**  I have my system working but I am trying to determine why it is reporting "Peak Grid Supply" (_Dark Purple on pwdusage image below)_ when it should not. 

Today for instance 12/26. At 18:00 the usage dashboard started reporting peak grid supply. 

I have included my usage.json file below. The "Peak" period for Non-summer is from 6:00 - 9:00. So I cannot determine why it started reporting peak usage at 18:00 ?

 For some reason it is using the "Summer" period which does have "Peak" at 18:00. 

 I believe I have the calendar programming set right... Summer for 2024-04-01 and Non-Summer 2024-10-01.

Do I have the calender section correct?

**Question #2:** This coming spring do I add another calendar to start 2025-04-01 or can there only be two calendar sections?

Thanks in advance for your help...

`{
    "settings": {
        "influx_url": "http://172.20.0.7:8086",
        "bucket": "powerwall/kwh",
        "timezone": "America/New_York",
        "supply_priority": [
            "GRID_SUPPLY",
            "PW_SUPPLY",
            "SOLAR_SUPPLY"
        ],
        "cost_unit": "$",
        "energy_unit": "kWh",
        "rename": {
            "GRID_SUPPLY": "Grid supply---",
            "GRID_EXPORT": "Grid export+++"
        },
        "resample": true,
        "week_anchor": "MONTH",
        "year_anchor": "JAN"        
    },
    "plans": [
        {
            "name": "Duke-RS-TC",
            "report": [
                "GRID_SUPPLY",
                "GRID_EXPORT",
                "SELF_PW_NET_OF_GRID",
                "SELF_SOLAR_PLUS_RES"
            ],
            "agent": "Simple",
            "seasons": {
                "Summer": [
                    {
                        "schedule": "Weekday",
                        "days": [
                            0,
                            1,
                            2,
                            3,
                            4
                        ],
                        "periods": {
                            "21:00": "Off-Peak",
                            "01:00": "Discount",
                            "06:00": "Off-Peak",
                            "18:00": "Peak"
                        }
                    },
                    {
                        "schedule": "Weekend",
                        "days": [
                            5,
                            6
                        ],
                        "periods": {
                            "00:00": "Off-Peak"
                        }
                    }
                ],
                "Non-Summer": [
                    {
                        "schedule": "Weekday",
                        "periods": {
                            "16:00": "Off-Peak",
                            "01:00": "Discount",
                            "03:00": "Off-Peak",
                            "06:00": "Peak",
                            "09:00": "Off-Peak",
                            "11:00": "Discount"
                        }
                    },
                    {
                        "schedule": "Weekend",
                        "days": [
                            5,
                            6
                        ],
                        "periods": {
                            "00:00": "Off-Peak"
                        }
                    }
                ]
            }
        }
    ],
    "calendar": {
        "2024-04-01": {
            "plan": "Duke-RS-TC",
            "season": "Summer",
            "tariffs": {
                "Peak": {
                    "GRID_SUPPLY": -0.223842,
                    "GRID_EXPORT": 0.223842,
                    "SELF_PW_NET_OF_GRID": 0.223842,
                    "SELF_SOLAR_PLUS_RES": 0.223842,
                    "SUPPLY_CHARGE": -0.019444444444
                },
                "Off-Peak": {
                    "GRID_SUPPLY": -0.097997,
                    "GRID_EXPORT": 0.097997,
                    "SELF_PW_NET_OF_GRID": 0.097997,
                    "SELF_SOLAR_PLUS_RES": 0.097997,
                    "SUPPLY_CHARGE": -0.01944444444
                },
                "Discount": {
                    "GRID_SUPPLY": -0.07848,
                    "GRID_EXPORT": 0.07848,
                    "SELF_PW_NET_OF_GRID": 0.07848,
                    "SELF_SOLAR_PLUS_RES": 0.07848,
                    "SUPPLY_CHARGE": -0.01944444444
            }
        },
        "2024-10-01": {
            "season": "Non-Summer",
            "tariffs": {
                "Peak": {
                    "GRID_SUPPLY": -0.223842,
                    "GRID_EXPORT": 0.223842,
                    "SELF_PW_NET_OF_GRID": 0.223842,
                    "SELF_SOLAR_PLUS_RES": 0.223842,
                    "SUPPLY_CHARGE": -0.01944444444
                },
                "Off-Peak": {
                    "GRID_SUPPLY": -0.097997,
                    "GRID_EXPORT": 0.097997,
                    "SELF_PW_NET_OF_GRID": 0.097997,
                    "SELF_SOLAR_PLUS_RES": 0.097997,
                    "SUPPLY_CHARGE": -0.01944444444
                },
                "Discount": {
                    "GRID_SUPPLY": -0.07848,
                    "GRID_EXPORT": 0.07848,
                    "SELF_PW_NET_OF_GRID": 0.07848,
                    "SELF_SOLAR_PLUS_RES": 0.07848,
                    "SUPPLY_CHARGE": -0.0194444444
                }
            }
        }
    }
}
}`

Powerwall Image and Pwdusagw image from today
<img width="865" alt="Screenshot 2024-12-26 at 6 48 03 PM" src="https://github.com/user-attachments/assets/648ea7f6-870f-468d-b7a3-2a2e63ebf592" />

<img width="439" alt="Screenshot 2024-12-26 at 6 48 25 PM" src="https://github.com/user-attachments/assets/5ebd9945-e6a2-4d56-a220-4757dc7b890d" />

**Comment by BuongiornoTexas** [comment]
Answering the easy question first, you can have as many calendar sections as you want. I use them for switching season and whenever the tariff updates (I've already got 6 or 7). The date order sorts itself out.

On your first question, your plan looks right, and I think you do have a little bit of peak power use between about 8:30 am and 9am. To get a better idea of what is going on with your grid use, click on the grid usage purple bar in the legend - this will turn off all of the other lines. Then zoom into the 8-10am range. If I'm reading your plot correctly, the powerwall stops supplying at about 8:30 and the grid takes over. If I'm misreading, then we'll need to do some deeper diagnostics.

**Comment by farberm** [comment]
Here is an updated graph from later today. The graph was almost entirely “Off-Peak” (except for the tiny blip around 7:45 am) until 18:00 tonight. Then starting at 18:00 the Peak Grip continues to increase.

I may be misinterpreting the graphs. I assume since there is only one small blip at 7:45 so Peek Grip supply should be almost zero and everything else “Off-Peak” The graph below are for today. The interesting thing is that on the weekend it works correctly with no “Peak” grid use showing.

Thanks again.

￼￼￼

**Comment by BuongiornoTexas** [comment]
Sorry - your graph didn't come through. Could you try again zoomed to the section I mentioned on the 26th? (8am to 10am). Mine looks like this.

![image](https://github.com/user-attachments/assets/2574752f-3f9e-4dad-8df7-5e8b2858ec12)

**Comment by BuongiornoTexas** [comment]
One more thing to check - your Non-Summer plan doesn't define the days array for the "Weekday". I'm not sure if this copies across from summer or not. If you want to be sure you should have a `"days": [0, 1, 2, 3, 4]` entry in Non-Summer.

**Comment by farberm** [comment]
Here is another try at the image..Only one small blip from 6:00 to 9:00?

￼

**Comment by farberm** [comment]
I will change that however…... I never see any peak usage on Sat and Sunday so I assume that was working correctly….

**Comment by farberm** [comment]
I have made the change and will check it tomorrow to see if that fixes the issue. Thanks and have a good holiday

**Comment by BuongiornoTexas** [comment]
> I never see any peak usage on Sat and Sunday so I assume that was working correctly….

That's what you would expect with your configuration.

**Comment by BuongiornoTexas** [comment]
> Here is another try at the image..Only one small blip from 6:00 to 9:00?

Unfortunately, I can't see this one either. Let's see if the other fix sorts things (you should be able to check easily - it doesn't modify the database, so any change to the configuration affects historical output globally).

**Comment by farberm** [comment]
Well that did not resolve the issue. I added three images here thru github hopefully you can see those.
<img width="466" alt="last 12" src="https://github.com/user-attachments/assets/4437dfcb-0a1e-42dc-8bbe-029bbcc41dda" />
<img width="782" alt="powerwall" src="https://github.com/user-attachments/assets/12d943d0-7834-49a2-b229-305639fed248" />

**Comment by farberm** [comment]
new usage.json file
`{
    "settings": {
        "influx_url": "http://172.20.0.7:8086",
        "bucket": "powerwall/kwh",
        "timezone": "America/New_York",
        "supply_priority": [
            "GRID_SUPPLY",
            "PW_SUPPLY",
            "SOLAR_SUPPLY"
        ],
        "cost_unit": "$",
        "energy_unit": "kWh",
        "rename": {
            "GRID_SUPPLY": "Grid supply---",
            "GRID_EXPORT": "Grid export+++"
        },
        "resample": true,
        "week_anchor": "MONTH",
        "year_anchor": "JAN"        
    },
    "plans": [
        {
            "name": "Duke-RS-TC",
            "report": [
                "GRID_SUPPLY",
                "GRID_EXPORT",
                "SELF_PW_NET_OF_GRID",
                "SELF_SOLAR_PLUS_RES"
            ],
            "agent": "Simple",
            "seasons": {
                "Summer": [
                    {
                        "schedule": "Weekday",
                        "days": [
                            0,
                            1,
                            2,
                            3,
                            4
                        ],
                        "periods": {
                            "01:00": "Discount",
                            "06:00": "Off-Peak",
                            "18:00": "Peak",
                            "21:00": "Off-Peak"
                        }
                    },
                    {
                        "schedule": "Weekend",
                        "days": [
                            5,
                            6
                        ],
                        "periods": {
                            "00:00": "Off-Peak"
                        }
                    }
                ],
                "Non-Summer": [
                    {
                        "schedule": "Weekday",
                        "days": [
                            0,
                            1,
                            2,
                            3,
                            4
                        ],
                        "periods": {
                            "01:00": "Discount",
                            "03:00": "Off-Peak",
                            "06:00": "Peak",
                            "09:00": "Off-Peak",
                            "11:00": "Discount",
                            "16:00": "Off-Peak"
                        }
                    },
                    {
                        "schedule": "Weekend",
                        "days": [
                            5,
                            6
                        ],
                        "periods": {
                            "00:00": "Off-Peak"
                        }
                    }
                ]
            }
        }
    ],
    "calendar": {
        "2024-04-01": {
            "plan": "Duke-RS-TC",
            "season": "Summer",
            "tariffs": {
                "Peak": {
                    "GRID_SUPPLY": -0.223842,
                    "GRID_EXPORT": 0.223842,
                    "SELF_PW_NET_OF_GRID": 0.223842,
                    "SELF_SOLAR_PLUS_RES": 0.223842,
                    "SUPPLY_CHARGE": -0.019444444444
                },
                "Off-Peak": {
                    "GRID_SUPPLY": -0.097997,
                    "GRID_EXPORT": 0.097997,
                    "SELF_PW_NET_OF_GRID": 0.097997,
                    "SELF_SOLAR_PLUS_RES": 0.097997,
                    "SUPPLY_CHARGE": -0.01944444444
                },
                "Discount": {
                    "GRID_SUPPLY": -0.07848,
                    "GRID_EXPORT": 0.07848,
                    "SELF_PW_NET_OF_GRID": 0.07848,
                    "SELF_SOLAR_PLUS_RES": 0.07848,
                    "SUPPLY_CHARGE": -0.01944444444
            }
        },
        "2024-10-01": {
            "season": "Non-Summer",
            "tariffs": {
                "Peak": {
                    "GRID_SUPPLY": -0.223842,
                    "GRID_EXPORT": 0.223842,
                    "SELF_PW_NET_OF_GRID": 0.223842,
                    "SELF_SOLAR_PLUS_RES": 0.223842,
                    "SUPPLY_CHARGE": -0.01944444444
                },
                "Off-Peak": {
                    "GRID_SUPPLY": -0.097997,
                    "GRID_EXPORT": 0.097997,
                    "SELF_PW_NET_OF_GRID": 0.097997,
                    "SELF_SOLAR_PLUS_RES": 0.097997,
                    "SUPPLY_CHARGE": -0.01944444444
                },
                "Discount": {
                    "GRID_SUPPLY": -0.07848,
                    "GRID_EXPORT": 0.07848,
                    "SELF_PW_NET_OF_GRID": 0.07848,
                    "SELF_SOLAR_PLUS_RES": 0.07848,
                    "SUPPLY_CHARGE": -0.0194444444
                }
            }
        }
    }
}
}
`

**Comment by BuongiornoTexas** [comment]
I haven't tested it, but I think the reason the Non-Summer calendar isn't firing is because it is missing a plan. Try adding `"plan": "Duke-RS-TC",` after `"2024-10-01: {`.

(Requiring the plan isn't as stupid as it looks - it allows you to change providers and/or tariffs over the life of your system.)

**Comment by farberm** [comment]
Just figured it out. I was missing a bracket "}" in the wrong place. At to end of the 2024-04-01 plan. Seems to be working now but I need to do some more testing. I will also add the plan after the 2024-10-01 line to be complete

**Comment by farberm** [comment]
Revised usage.json file

`{
    "settings": {
        "influx_url": "http://172.20.0.7:8086",
        "bucket": "powerwall/kwh",
        "timezone": "America/New_York",
        "supply_priority": [
            "GRID_SUPPLY",
            "PW_SUPPLY",
            "SOLAR_SUPPLY"
        ],
        "cost_unit": "$",
        "energy_unit": "kWh",
        "rename": {
            "GRID_SUPPLY": "Grid supply---",
            "GRID_EXPORT": "Grid export+++"
        },
        "resample": true,
        "week_anchor": "MONTH",
        "year_anchor": "JAN"        
    },
    "plans": [
        {
            "name": "Duke-RS-TC",
            "report": [
                "GRID_SUPPLY",
                "GRID_EXPORT",
                "SELF_PW_NET_OF_GRID",
                "SELF_SOLAR_PLUS_RES"
            ],
            "agent": "Simple",
            "seasons": {
                "Summer": [
                    {
                        "schedule": "Weekday",
                        "days": [
                            0,
                            1,
                            2,
                            3,
                            4
                        ],
                        "periods": {
                            "21:00": "Off-Peak",
                            "01:00": "Discount",
                            "06:00": "Off-Peak",
                            "18:00": "Peak"
                        }
                    },
                    {
                        "schedule": "Weekend",
                        "days": [
                            5,
                            6
                        ],
                        "periods": {
                            "00:00": "Off-Peak"
                        }
                    }
                ],
                "Non-Summer": [
                    {
                        "schedule": "Weekday",
                        "days": [
                            0,
                            1,
                            2,
                            3,
                            4
                        ],
                        "periods": {
                            "16:00": "Off-Peak",
                            "01:00": "Discount",
                            "03:00": "Off-Peak",
                            "06:00": "Peak",
                            "09:00": "Off-Peak",
                            "11:00": "Discount"
                        }
                    },
                    {
                        "schedule": "Weekend",
                        "days": [
                            5,
                            6
                        ],
                        "periods": {
                            "00:00": "Off-Peak"
                        }
                    }
                ]
            }
        }
    ],
    "calendar": {
        "2024-04-01": {
            "plan": "Duke-RS-TC",
            "season": "Summer",
            "tariffs": {
                "Peak": {
                    "GRID_SUPPLY": -0.223842,
                    "GRID_EXPORT": 0.223842,
                    "SELF_PW_NET_OF_GRID": 0.223842,
                    "SELF_SOLAR_PLUS_RES": 0.223842,
                    "SUPPLY_CHARGE": -0.019444444444
                },
                "Off-Peak": {
                    "GRID_SUPPLY": -0.097997,
                    "GRID_EXPORT": 0.097997,
                    "SELF_PW_NET_OF_GRID": 0.097997,
                    "SELF_SOLAR_PLUS_RES": 0.097997,
                    "SUPPLY_CHARGE": -0.01944444444
                },
                "Discount": {
                    "GRID_SUPPLY": -0.07848,
                    "GRID_EXPORT": 0.07848,
                    "SELF_PW_NET_OF_GRID": 0.07848,
                    "SELF_SOLAR_PLUS_RES": 0.07848,
                    "SUPPLY_CHARGE": -0.01944444444
                }    
            }
        },

        "2024-10-01": {
            "season": "Non-Summer",
            "tariffs": {
                "Peak": {
                    "GRID_SUPPLY": -0.223842,
                    "GRID_EXPORT": 0.223842,
                    "SELF_PW_NET_OF_GRID": 0.223842,
                    "SELF_SOLAR_PLUS_RES": 0.223842,
                    "SUPPLY_CHARGE": -0.01944444444
                },
                "Off-Peak": {
                    "GRID_SUPPLY": -0.097997,
                    "GRID_EXPORT": 0.097997,
                    "SELF_PW_NET_OF_GRID": 0.097997,
                    "SELF_SOLAR_PLUS_RES": 0.097997,
                    "SUPPLY_CHARGE": -0.01944444444
                },
                "Discount": {
                    "GRID_SUPPLY": -0.07848,
                    "GRID_EXPORT": 0.07848,
                    "SELF_PW_NET_OF_GRID": 0.07848,
                    "SELF_SOLAR_PLUS_RES": 0.07848,
                    "SUPPLY_CHARGE": -0.0194444444
                }
            }
        }
    }
}

`

**Comment by BuongiornoTexas** [comment]
> Just figured it out.

Ah - I see it now. JSON validation is definitely weak in the module (sorry!). Glad you found it and got it working!
